### ISSUE TITLE
Product - add an alternative domain

### ISSUE THREAD

**Issue by dnl-blkv** [saadq/resumake#27]
How to Reproduce
------------------
1. Try to recall the latexresu.me domain name.

What Should Happen
---------------------
1. The domain name is easy to remember/recall, especially for non-tech people: tech people can use LaTeX themselves.

What Happens
---------------
1. The domain name is quite technical (features underlying technology name), and recalling it is a bit of a counterintuitive task.

Notes
------
1. My suggestion is to add one of the following as an alternative domain name (all the domains are unregistered!):
    - https://makeresu.me
    - https://buildresu.me 
    - https://createresu.me
2. Other not-so-tech options would also work just alright :)
3. May be it would even be better to set the new domain name main and redirect from https://latexresu.me to it.
4. Feedback is very welcome! :)

**Comment by saadq** [comment]
This is a good idea. Because this is an app that is supposed to cater to everyone (not just tech people), it would probably be better to keep the `LaTeX` part as an implementation detail, and then just market it as an all-purpose Resume Generator.

I like all 3 of the domain names you suggested, maybe we could treat this issue as a poll and it would be great if people could vote on the following options:

# Total Votes
* makeresu.me: **0**
* buildresu.me: **0**
* createresu.me: **1**

I'll vote on `createresu.me` to start off with. If anyone finds this issue, please vote as well (including you OP!)

I'll leave this issue open for maybe about a week and then decide afterwards.

**Comment by dnl-blkv** [comment]
My vote is for for `buildresu.me`. The reasoning behind that is that the site allows to _build_ resume from pre-defined blocks which were _created_ by someone else :)

**Comment by shivakrishna9** [comment]
I vote for latexresu.me only because, I am able to discover this by searching by keyword `latex` .
Thank you for the amazing app.

**Comment by saadq** [comment]
Hey all, I know it's been a crazy long amount of time, but I have been working on a new version of the site. There are still a lot of things that need to be done, but the new name of the webapp is `Resumake`, so I thought `makeresu.me` would be the most appropriate domain. Thanks for all the feedback!

The new version already has importing/exporting the resume as JSON (compatible with `JSONResume`), saving your current session, and I'm waiting on LinkedIn to authorize my app so that I can allow users to import their LinkedIn profile. It was also a full code rewrite and a bit of a modified design.

In case you're curious on progress, you can check out the [new](https://github.com/saadq/latexresu.me/tree/new) branch for updates. Excited to get this done!

Before:

![screen shot 2017-11-21 at 5 18 43 pm](https://user-images.githubusercontent.com/5678694/33099890-83558946-cee0-11e7-97cf-0aa021193330.png)

After:

![screen shot 2017-11-21 at 5 18 52 pm](https://user-images.githubusercontent.com/5678694/33099895-8692fd6e-cee0-11e7-9a66-a5666a1b748b.png)

**Comment by saadq** [comment]
https://resumake.io is live now! Please let me know if you guys have any feedback :)
